version: "3"
services:
  web:
    depends_on:
      - db
    image: amaz-mod
    restart: on-failure
    ports: 
      - 1337:1337
    networks:
      - webnet
  prox:
    image: amaz-prox
    restart: on-failure
    ports:
      - 3003:3003
  db:
    image: couchdb:latest
    restart: on-failure
    volumes:
    - couchdb-data-volume:/usr/local/var/lib/couchdb
    networks:
      - webnet
    ports:
      - 5984:5984
volumes: 
  couchdb-data-volume:
networks:
  webnet: